# MACHINE LEARNING: USING SUPPORT VECTOR MACHINE ALGO


In [7]:
from sklearn import datasets
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [8]:
#Using in-built data set
mydata=datasets.load_digits()

In [9]:
X_input=mydata.data

In [10]:
Y_target=mydata.target

In [11]:
print("Shape of data is {} and shape of target is {} ".format(X_input.shape,Y_target.shape))

Shape of data is (1797, 64) and shape of target is (1797,) 


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
#Splitting
X_train,X_test,Y_train,Y_test=train_test_split(X_input,Y_target,test_size=.30,random_state=101)

In [14]:
print("Shape of X_train {} and shape of X_test {}" .format(X_train.shape,X_test.shape))

Shape of X_train (1257, 64) and shape of X_test (540, 64)


In [15]:
print("Shape of Y_train {} and shape of Y_test {} " .format(Y_train.shape,Y_test.shape))

Shape of Y_train (1257,) and shape of Y_test (540,) 


In [16]:
from sklearn.svm import SVC

In [17]:
trainer=SVC(gamma=.001)

In [18]:
learner=trainer.fit(X_train,Y_train)

In [19]:
#predict
Ya=Y_test
Yp=learner.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,jaccard_similarity_score

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
acc=accuracy_score(Ya,Yp)
jss=jaccard_similarity_score(Ya,Yp)
cm=confusion_matrix(Ya,Yp)
cr=classification_report(Ya,Yp)

In [23]:
print("acc is {} and jss is {}" .format(acc,jss))

acc is 0.9925925925925926 and jss is 0.9925925925925926


In [24]:
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       0.96      1.00      0.98        55
           2       1.00      1.00      1.00        49
           3       1.00      1.00      1.00        54
           4       1.00      0.98      0.99        61
           5       1.00      0.98      0.99        59
           6       1.00      1.00      1.00        46
           7       1.00      1.00      1.00        56
           8       1.00      0.97      0.98        59
           9       0.96      1.00      0.98        48

   micro avg       0.99      0.99      0.99       540
   macro avg       0.99      0.99      0.99       540
weighted avg       0.99      0.99      0.99       540



In [25]:
from scipy import misc

In [31]:
myimage=misc.imread(r"8.jpg")

C:\Users\Surbhi Varshney\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


In [32]:
print(mydigit)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [33]:
print(myimage.shape)

(256, 256, 3)


In [34]:
#change digit image into 8*8

In [35]:
mydigit_88=misc.imresize(myimage,(8,8))

C:\Users\Surbhi Varshney\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  """Entry point for launching an IPython kernel.


In [36]:
print("Shape of myimage {}".format(mydigit_88.shape))

Shape of myimage (8, 8, 3)


In [37]:
print("data type of myimage_88 {}".format(mydigit_88.dtype))

data type of myimage_88 uint8


In [38]:
#To change data type to the format of X_input's data type
mydigit_float=mydigit_88.astype(X_input.dtype)

In [39]:
print("dtype of mydigit_float {}" .format(mydigit_float.dtype
                                         
                                         ))

dtype of mydigit_float float64


In [41]:
mydigit_float

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.],
        [22., 22., 22.],
        [35., 35., 35.],
        [33., 33., 33.],
        [ 6.,  6.,  6.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 8.,  8.,  8.],
        [27., 27., 27.],
        [ 1.,  1.,  1.],
        [16., 16., 16.],
        [19., 19., 19.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 9.,  9.,  9.],
        [26., 26., 26.],
        [ 0.,  0.,  0.],
        [14., 14., 14.],
        [19., 19., 19.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.],
        [25., 25., 25.],
        [27., 27., 27.],
        [42., 42., 42.],
        [14., 14., 14.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [13., 13., 13.],
        [39., 39., 39.],
        [31., 31., 31.],
        [30., 30., 30.],
        [ 6.,  6.,  6.],
        [ 0.,  0.

In [42]:
#feature scaling...down scaling in the range 0 to 16

In [44]:
mydigit_scale=misc.bytescale(mydigit_float,high=16,low=0)

C:\Users\Surbhi Varshney\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `bytescale` is deprecated!
`bytescale` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
  """Entry point for launching an IPython kernel.


In [45]:
mydigit_scale

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8],
        [13, 13, 13],
        [13, 13, 13],
        [ 2,  2,  2],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 3,  3,  3],
        [10, 10, 10],
        [ 0,  0,  0],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 3,  3,  3],
        [10, 10, 10],
        [ 0,  0,  0],
        [ 5,  5,  5],
        [ 7,  7,  7],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [10, 10, 10],
        [10, 10, 10],
        [16, 16, 16],
        [ 5,  5,  5],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 5,  5,  5],
        [15, 15, 15],
        [12, 12, 12],
        [11, 11, 11],
        [ 2,  2,  2],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 4,  4,  4],
        [11, 11, 11],
        [ 2,  2,  2],
        [ 0,  0,  0],


In [46]:
mydigit_newtype=mydigit_scale.astype(X_input.dtype
                                    )

In [47]:
print("data type is {}" .format(mydigit_newtype.dtype))

data type is float64


In [48]:
mydigit_newtype

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 8.,  8.,  8.],
        [13., 13., 13.],
        [13., 13., 13.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [10., 10., 10.],
        [10., 10., 10.],
        [16., 16., 16.],
        [ 5.,  5.,  5.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [15., 15., 15.],
        [12., 12., 12.],
        [11., 11., 11.],
        [ 2.,  2.,  2.],
        [ 0.,  0.

In [49]:
mydigit_newtype.shape

(8, 8, 3)

In [51]:
x_testimage=[]
for eachrow in mydigit_newtype:
    for eachpixel in eachrow:
        x_testimage.append(sum(eachpixel)/3.0
                          )

In [52]:
len(x_testimage)

64

In [54]:
type(x_testimage)

list

In [ ]:
#But since we need array for prediction:

In [55]:
image_array=np.array(x_testimage)

In [58]:
learner.predict([image_array])

array([8])